name: update.sh

on:
  pull_request:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for Changes
        run: |
          hash_before="$(git write-tree)"
          ./update.sh
          git add -A
          [[ "$hash_before" = "$(git write-tree)" ]]
